version: "2"
services:
  wordpress:
    build: .
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    volumes:
      - ./:/var/www/html/wp-content/plugins/moovly

  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 33360:3306
    environment:
      MYSQL_DATABASE: moovly
      MYSQL_USER: moovly
      MYSQL_PASSWORD: moovly
      MYSQL_RANDOM_ROOT_PASSWORD: 1